# Generated by Django 3.2.13 on 2022-07-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crud_fdv_model',
            new_name='employee_crud_fdv_model',
        ),
    ]
