# Generated by Django 3.2.13 on 2022-07-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_rename_eadd_book_crud_fdv_model_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book_crud_fdv_model',
            new_name='book_crud_cdv_model',
        ),
    ]
